# Generated by Django 3.1 on 2021-08-02 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_auto_20210802_0225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cartID',
            new_name='cart_id',
        ),
    ]
